Specify a ContextConfiguration for SpringBootServerRestControllerTest
Without this annotation, the following exception would be thrown:
 java.lang.IllegalStateException: Unable to find a @SpringBootConfiguration, you need to use @ContextConfiguration or @SpringBootTest(classes=...) with your test